config/routes.rb
Rails.application.routes.draw do
  resources :logins
  get 'data/index' 
  
 

    root 'logins#index'
    

end

app/models/login.rb
class Login < ActiveRecord::Base
	require 'open-uri'

	validates :Username, :presence => true
	validates :Region, :presence => true
	validate :valid_name


 def valid_name
   	username=read_attribute(:Username)
    region=read_attribute(:Region)
 	result="https://"+region.to_s+".api.pvp.net/api/lol/"+region.to_s+"/v1.4/summoner/by-name/"+username.to_s+"?api_key=28ba1d65-cda8-4e79-90ad-aad6b1ab6326"

 	begin
 		value=open(result)

		#status=value.stats[0]
		#if status.to_i!=200
		#	errors.add(:login,status)
		#end
	
 	#rescue OpenURI::HTTPError
 	#	errors.add(:login, "champion name may have been entered incorrectly")
 	#rescue SocketError
 	#	errors.add(:Please, "make sure that the Username AND Region were entered correctly")
 	#end
	end
	uri=URI.parse(result)
	
	str=uri.read
	lvl=JSON.parse(str)[username]["summonerLevel"]

	if lvl.to_i!=30
		errors.add(:Champion, "is not level 30")
	end
 	rescue SocketError
 		errors.add(:login, "champion name may have been entered incorrectly")
 	rescue URI::InvalidURIError
		errors.add(:Issue, "make sure you entered everything correctly")
	rescue OpenURI::HTTPError
 		errors.add(:login, "champion name may have been entered incorrectly")
 	end

  

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]
  
  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:Username, :Region)
    end





end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Username %><br>
    <%= f.text_field :Username%>
 

 
<div class="field">
    <%= f.label :Region %><br>
    <p id="region_options">[BR, EUNE, EUW, KR, LAN, LAS, NA, OCE, RU, TR]</p>
    <%= f.text_field :Region %>
  </div>




  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

 

app/views/logins/edit.html.erb
<div class="new_status">
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>
</div>

app/views/logins/index.html.erb
<body id="background">
    <div class="page-header">
      <div class="center-block">
      <h1>Welcome to LOLAnalytic</h1>
      <p>The most personal League of Legends tool yet</p>
    </div>
    </div>


    <table>
      <thead>
        <tr>

         
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @logins.each do |login| %>
          <tr>
            
              <td div class='username' id='login<%=login.id%>'>
                <%= login.Username%>
              </td>

              <td><%= link_to 'Edit', edit_login_path(login), :id => 'edit_option' %></td>
              <td><%= link_to 'Delete', login, method: :delete, data: { confirm: 'Are you sure?' }, :id => 'destroy_option' %></td>
              <td><%= link_to 'Stats', data_index_path(params: login.attributes), :id => 'stats_option' %></td>

            <p>
              
            </p>
          </tr>
        <% end %>
      </tbody>
    </table>

     

    <br>
    <div class="login_button">
      <%= link_to 'Login', new_login_path, class:"btn btn-success" %>
    </div>
        

    <footer id="disclaimer">
        <p>
          
          LOLAnalytic isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.
        </p>
      </footer>
</body>

app/views/logins/new.html.erb
<div class="new_status">
	<h1>Login</h1>

	<%= render 'form' %>

	<%= link_to 'Back', logins_path %>
</div>

app/views/logins/show.html.erb
<div class="new_status">
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @login.Username %>
</p>

<p>
  <strong>Region:</strong>
  <%= @login.Region %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>
</div>